apiVersion: v1
kind: List
metadata: {}
items:
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      pipeline.alpha.openshift.io/uses: '[{"name": "popular-movie-store", "namespace": "", "kind": "DeploymentConfig"},{"name": "popular-movie-store-canary", "namespace": "", "kind": "DeploymentConfig"}]'
    name:  popular-movie-store-pipeline
  spec:
    source:
      git:
        ref: pipeline
        uri: https://github.com/kameshsampath/inifinispan-demo-apps/popular-movie-store.git
      type: Git
    strategy:
      type: JenkinsPipeline
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
    - generic:
        secret: infini5p@n
      type: Generic