moviestore:
  apiEndpointUrl: "https://api.themoviedb.org/3"
  apiKey: "${API_KEY}"
infinispan:
  embedded:
    config-xml: infinispan-moviestore.xml
spring:
  thymeleaf:
    mode: HTML
    cache: false

